---
- name: add the docker repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xD8576A8BA88D21E9 state=present

- name: add the docker repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

- name: install docker
  apt: pkg=lxc-docker state=present update_cache=true
